### ISSUE TITLE
Please contact me about this repo contents

### ISSUE THREAD

**Issue by ragdelaed** [Deepanjalkumar/binaryedge#1]
Hello, my name is Eddy, I work at BMS, please contact me when you get this regarding this repo contents, specifically, 

**https://github.com/Deepanjalkumar/binaryedge/blob/59cc29577a4d04b5398740fc6f56b266d2328928/data/subdomain/bms.com.txt**

I am asking if you would remove this page please. Thanks.

Mobile: +1.678.630.6112
Email:edgar.deal@bms.com

**Comment by Deepanjalkumar** [comment]
Thanks for reaching out. The issue had been resolved.
